#Women Cloth Reviews Prediction with Multinomal Naive Bayes


The multinomial naive bayes classifier is suitable for classification with discrete features .
The multinomial distribution normally requires integer feature count. However , in practice, fractional count such as tf_idf may also work.

#import library

In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


#import dataset

In [20]:
df = pd.read_csv('https://github.com/YBIFoundation/MachineLearning/raw/main/Dataset/Women%20Clothing%20E-Commerce%20Review.csv')

In [21]:
df.head()

Clothing ID  Age                    Title  \
0          767   33                      NaN   
1         1080   34                      NaN   
2         1077   60  Some major design flaws   
3         1049   50         My favorite buy!   
4          847   47         Flattering shirt   

                                              Review  Rating  Recommended  \
0  Absolutely wonderful - silky and sexy and comf...       4            1   
1  Love this dress!  it's sooo pretty.  i happene...       5            1   
2  I had such high hopes for this dress and reall...       3            0   
3  I love, love, love this jumpsuit. it's fun, fl...       5            1   
4  This shirt is very flattering to all due to th...       5            1   

   Positive Feedback        Division Department   Category  
0                  0       Initmates   Intimate  Intimates  
1                  4         General    Dresses    Dresses  
2                  0         General    Dresses    Dresses  
3                  0  General Petite    Bottoms      Pants  
4                  6         General       Tops    Blouses

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   Clothing ID        23486 non-null  int64 
 1   Age                23486 non-null  int64 
 2   Title              19676 non-null  object
 3   Review             22641 non-null  object
 4   Rating             23486 non-null  int64 
 5   Recommended        23486 non-null  int64 
 6   Positive Feedback  23486 non-null  int64 
 7   Division           23472 non-null  object
 8   Department         23472 non-null  object
 9   Category           23472 non-null  object
dtypes: int64(5), object(5)
memory usage: 1.8+ MB


In [24]:
df.shape

(23486, 10)

#Missing values

In [25]:
df.isna().sum()

Clothing ID             0
Age                     0
Title                3810
Review                845
Rating                  0
Recommended             0
Positive Feedback       0
Division               14
Department             14
Category               14
dtype: int64

In [29]:
df[df['Review']==""]=np.NaN

In [30]:
df['Review'].fillna("No Review",inplace=True)

In [31]:
df.isna().sum()

Clothing ID             0
Age                     0
Title                3810
Review                  0
Rating                  0
Recommended             0
Positive Feedback       0
Division               14
Department             14
Category               14
dtype: int64

In [32]:
df['Review']

0        Absolutely wonderful - silky and sexy and comf...
1        Love this dress!  it's sooo pretty.  i happene...
2        I had such high hopes for this dress and reall...
3        I love, love, love this jumpsuit. it's fun, fl...
4        This shirt is very flattering to all due to th...
                               ...                        
23481    I was very happy to snag this dress at such a ...
23482    It reminds me of maternity clothes. soft, stre...
23483    This fit well, but the top was very see throug...
23484    I bought this dress for a wedding i have this ...
23485    This dress in a lovely platinum is feminine an...
Name: Review, Length: 23486, dtype: object

#Define target (y) features (x)

In [33]:
df.columns

Index(['Clothing ID', 'Age', 'Title', 'Review', 'Rating', 'Recommended',
       'Positive Feedback', 'Division', 'Department', 'Category'],
      dtype='object')

In [34]:
x=df['Review']

In [35]:
y=df['Rating']

In [37]:
df['Rating'].value_counts()

Rating
5    13131
4     5077
3     2871
2     1565
1      842
Name: count, dtype: int64

#Train Test Split

In [38]:
from sklearn.model_selection import train_test_split

In [39]:
x_train,x_test,y_train,y_test=train_test_split(x, y, train_size = 0.7,stratify = y, random_state = 2529)

In [40]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((16440,), (7046,), (16440,), (7046,))

#Get features text conversion to token

In [41]:
from sklearn.feature_extraction.text import CountVectorizer

In [42]:
cv = CountVectorizer(lowercase = True, analyzer = 'word',ngram_range=(2,3),stop_words = 'english', max_features=5000)

In [43]:
x_train = cv.fit_transform(x_train)


In [44]:
cv.get_feature_names_out()

array(['10 12', '10 bought', '10 fit', ..., 'yellow color', 'yoga pants',
       'zipper little'], dtype=object)

#Get model train

In [49]:
from sklearn.naive_bayes import MultinomialNB

In [50]:
model = MultinomialNB()

In [51]:
model.fit(x_train,y_train)

MultinomialNB()

In [56]:
x_test_transformed = cv.transform(x_test)

#Get model prediction

In [57]:
y_pred = model.predict(x_test_transformed)

In [58]:
y_pred.shape

(7046,)

In [59]:
y_pred

array([2, 5, 5, ..., 5, 5, 5])

#Get property of each predicted class

In [61]:
model.predict_proba(x_test_transformed)

array([[1.74888226e-02, 8.00167127e-01, 1.76552240e-01, 3.67359395e-03,
        2.11821605e-03],
       [9.61254713e-02, 4.94430566e-02, 1.39233267e-01, 1.19881647e-01,
        5.95316558e-01],
       [3.58272506e-02, 6.66058394e-02, 1.22262774e-01, 2.16180049e-01,
        5.59124088e-01],
       ...,
       [3.51001766e-02, 1.03900602e-01, 1.82117867e-01, 2.40496082e-01,
        4.38385273e-01],
       [6.15772480e-06, 6.58842730e-05, 4.11503585e-05, 6.71256438e-04,
        9.99215551e-01],
       [1.53903207e-05, 1.92970287e-07, 1.81822735e-05, 2.58111041e-03,
        9.97385124e-01]])

#Get model evaluation

In [62]:
from sklearn.metrics import confusion_matrix,classification_report

In [63]:
print(confusion_matrix(y_test,y_pred))

[[  33   43   53   27   97]
 [  25   87  143   74  141]
 [  20   96  274  199  272]
 [  15   48  171  385  904]
 [  13   40  132  398 3356]]


In [64]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       0.31      0.13      0.18       253
           2       0.28      0.19      0.22       470
           3       0.35      0.32      0.34       861
           4       0.36      0.25      0.30      1523
           5       0.70      0.85      0.77      3939

    accuracy                           0.59      7046
   macro avg       0.40      0.35      0.36      7046
weighted avg       0.54      0.59      0.56      7046



#Get model re-train

In [68]:
from sklearn.naive_bayes import MultinomialNB

In [69]:
model = MultinomialNB()

In [70]:
model.fit(x_train , y_train)

MultinomialNB()

#Get model evaluation

In [72]:
from sklearn.metrics import confusion_matrix,classification_report

In [73]:
print(confusion_matrix(y_test,y_pred))

[[  33   43   53   27   97]
 [  25   87  143   74  141]
 [  20   96  274  199  272]
 [  15   48  171  385  904]
 [  13   40  132  398 3356]]


In [74]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       0.31      0.13      0.18       253
           2       0.28      0.19      0.22       470
           3       0.35      0.32      0.34       861
           4       0.36      0.25      0.30      1523
           5       0.70      0.85      0.77      3939

    accuracy                           0.59      7046
   macro avg       0.40      0.35      0.36      7046
weighted avg       0.54      0.59      0.56      7046

